### ISSUE TITLE
Solidify Workflows

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#267]
## To-Dos
- [ ] Add this to the docs
- [x] Use **NEW** as State instead of **INITIALIZED**, remove **INITIALIZED.**
- [x] Remove **ORDER_STATUS_PENDING** Status
- [x] Remove unsed **ON_HOLD** State
- [ ] Add Status to backend Overview (list and detail)
- [ ] Add Workflow Description to State Overview in Order Detail
- [x] Implement Translations for States and Status To Frontend
- [ ] Implement Translations for States and Status To Backend
- [ ] Display Status in Customer Order Overview
- [x] Implement Statuses: **WAITING_FOR_PAYMENT** (To pending payment state), **SHIPPED** (To complete state), **ON_HOLD** (To processing state)
- [x] Rename **CLOSED** Status to **REFUNDED**
- [ ] Strict State Config in Workflow (Transitions): Do not allow to change State (in Backend) if not possible
- [ ] Implement Status change functionality to payment (?)

## Order States

> These are the default States and Statuses which comes shipped with CoreShop.

**State**: Used by Core and Backend. It's not possible to add custom States!
**Status**: Used to display to User in Frontend (Order Overview). It's possible to add custom status fields to give frontend customer a better overview about his current order state.

| State  | Status |  Description  | Comments
|-------|--------|--------------|-----------|
| **~INITIALIZED~**  | INITIALIZED | The Default State when creating an Order Object | Remove it since it has no meaning to customer and/or backend office? |
| **NEW**  | NEW | A new Order has been placed. | This State is actually not implemented. We should use this State instead of INITIALIZED |
| **PENDING_PAYMENT**  | WAITING_FOR_PAYMENT, PENDING_PAYMENT | This is a difficult one. This State gets applied if users choose offline payment or if payment gateway wants to manually capture the payment. Depending on selection the status will change to WAITING_FOR_PAYMENT or PENDING_PAYMENT.  | |
| **PAYMENT_REVIEW**  | PAYMENT_REVIEW | If something went wrong during payment (wrong amount, fraud detection) this state gets applied. | |
| **PROCESSING**  | PROCESSING | Processing means that orders are currently in processing state. | |
| **COMPLETE**  | SHIPPED | Orders marked as complete have been invoiced and have shipped. | |
| **CLOSED**  | REFUNDED | Closed orders are orders that have had a credit memo assigned to it and the customer has been refunded for their order. | Rename CLOSED Status to REFUNDED |
| **CANCELED**  | CANCELED | Cancelled orders should be used if orders are cancelled or if the orders have not been paid for. | |
| **~ON_HOLD~**  | ON_HOLD | Orders placed on hold must be taken off hold before continuing any further actions. | Remove it! Since we can't switch back to PROCESSING, we should add ON_HOLD as a Status to _PROCESSING_ |

## Payment States

| State  | Description  | Comments
|-------|-------------|-----------|
| **NEW**  | Payment has been created. This happens after customer hits the 'buy' button in checkout summary. | |
| **PROCESSING**  | If payment has been authorized | |
| **COMPLETED**  | Payment has been successfully captured. | |
| **FAILED**  | Guess what. | |
| **CANCELLED**  | Payment has been canceled on gateway side. | |
| **REFUNDED**  | Payment has been refunded. | |
| **UNKNOWN**  | Status is unknown. | |

**Comment by dpfaffenbauer** [comment]
Transitions need to be defined as well.

**Comment by solverat** [comment]
This ticket is not relevant anymore since we're now using the symfony state machine, see #276.
