### ISSUE TITLE
Implement State Machine

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#276]
We decided to remove the pimcore workflow and use the symfony state machine instead. There will be several state machines:

- **order state** (main order state which can't be changed manually)
- **payment state** (current states of one or more payments)
- **order payment state** (current payment state of all payments combined)
- **shipping state** (current states of one or more shippments)
- **order shipping state** (current shipping state of all shipmments combined)
- **invoice state** (current states of one or more invoices)
- **order invoice state** (current invoice state of all invoices combined)

This will also make #267 obsolete.

## Todo

- [x] Remove Pimcore Workflow completely
- [x] Implement State Machine
  - [x] Implement Order*StateResolver
  - [x] Add Persistence to State Change (ORM & Concrete)
  - [x] Allow Callbacks to each transition
  - [x] Implement Cascade Transitions
- [x] Add Order State and all Sub-States to Order Backend and List
  - [x] Show translated Order State on Top
  - [x] Show translated Sub-States below:  _payment state_, _shipping state_, _invoice state_
- [x] Backend: Add State-Change function to backend to _payment_, _shipping_, _invoice_
- [x] _payment_, _shipping_, _invoice_: each of them should be available through a service api (create, change state) Used by Backend or via API
- [x] Update FrontendBundle: User Order-Overview State Display
- [x] Update NotificationRules
- [x] Update Reports
